name: Cleanup Template Repository
on:
  create:
    types:
      - created
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Delete .github directory
        run: |
          rm -rf .github
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "chore: cleanup template repository files"
          git push
