version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automerge"
    versioning-strategy: auto
    ignore:
      - dependency-name: "eslint"
      - dependency-name: "eslint-*"
      - dependency-name: "@typescript-eslint/*"
      - dependency-name: "stylelint"
      - dependency-name: "stylelint-*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automerge"
